# NumPy

The tutorial on NumPy is heavily borrowed from the NumPy website; [https://numpy.org/devdocs/user/quickstart.html](https://numpy.org/devdocs/user/quickstart.html)

NumPy (num-pie) or "Numerical Python" is a Python library that undergirds almost all of Python's advanced mathematical and statistical functions. You might not use it too much directly but you'll be interacting with it constantly through other libraries. 

The core of NumPy are the NumPy arrays which are kind of like very advanced Python Lists.

In [2]:
import numpy as np

a = np.array([2, 3, 4])

a

array([2, 3, 4])

Make sure you use a list to create an array, the below is wrong

> b = np.array(2, 3, 4)

In [5]:
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In [7]:
c2 = np.array([12,34,56,78,90,113,14,15,16]).reshape(3,3)
c2

array([[ 12,  34,  56],
       [ 78,  90, 113],
       [ 14,  15,  16]])

## In the code blocks below d(x) are a 3-dimensional arrays

In [7]:
d = np.array([12,23,34,45,34,12,34,45,12,12,12,12]).reshape(3,2,2)
d

array([[[12, 23],
        [34, 45]],

       [[34, 12],
        [34, 45]],

       [[12, 12],
        [12, 12]]])

reshape = 3* 2x2

array([[[12, 23],
        [34, 45]],

       [[34, 12],
        [34, 45]],

       [[12, 12],
        [12, 12]]])

below, is a 2* 3x2 array

In [8]:
d2 = np.array([12,23,34,45,34,12,34,45,12,12,12,12]).reshape(2,3,2)
d2

array([[[12, 23],
        [34, 45],
        [34, 12]],

       [[34, 45],
        [12, 12],
        [12, 12]]])

In [6]:
d3 = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2, 2, 2)
d3

array([[[2, 3],
        [4, 5]],

       [[6, 2],
        [3, 5]]])

# NumPy Calculations

In [11]:
e = np.array([1,2,3,4,5,6])

print(e.sum())
print(e.min())
print(e.max())
print(e.mean())

e2 = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2, 2, 2)

print(e2.sum())
print(e2.min())
print(e2.max())
print(e2.mean())

# interesting that the reshaped arrays do not affect the calculations

21
1
6
3.5
30
2
6
3.75


### Special NumPy Arrays

These are some useful arrays that you can quickly create in NumPy. Don't worry too much about learning them now but it'll be useful to have a cheatsheet of them nearby.

np.zeros(5) # Creates an array of zeros with 5 elements
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # A random integer between 1 and 1000
np.arange(25) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25

In [12]:
print(np.zeros(5)) # Creates an array of zeros with 5 elements
print(np.linspace(0, 6, 10)) # Creates an array of values from 0 through 6 in 10 even spaces
print(np.random.rand(3)) # Three random values between 0 and 1
print(np.random.randint(1, 1000)) # A random integer between 1 and 1000
print(np.arange(25)) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25

[0. 0. 0. 0. 0.]
[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
[0.00756608 0.49058303 0.13162369]
541
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
