# NumPy

The tutorial on NumPy is heavily borrowed from the NumPy website; [https://numpy.org/devdocs/user/quickstart.html](https://numpy.org/devdocs/user/quickstart.html)

NumPy (num-pie) or "Numerical Python" is a Python library that undergirds almost all of Python's advanced mathematical and statistical functions. You might not use it too much directly but you'll be interacting with it constantly through other libraries. 

The core of NumPy are the NumPy arrays which are kind of like very advanced Python Lists.

In [3]:
import numpy as np

a = np.array([2, 3, 4])

a

array([2, 3, 4])

Make sure you use a list to create an array, the below is wrong

> b = np.array(2, 3, 4)

In [5]:
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In [7]:
c2 = np.array([12,34,56,78,90,113,14,15,16]).reshape(3,3)
c2

array([[ 12,  34,  56],
       [ 78,  90, 113],
       [ 14,  15,  16]])